export const ADD_WRONG_WORK = 'ADD_WRONG_WORK';
export const ADD_UNVERIFIED_WORK = 'ADD_UNVERIFIED_WORK';
export const REFRESH_PORTFOLIO = 'REFRESH_PORTFOLIO';
export const CHANGE_ROUTE = 'CHANGE_ROUTE';